# Assignment Questions
1.Using Numpy to generate an array of 25 random numbers sampled from a standard normal distribution

In [5]:
import numpy as np
np.random.rand(25)

array([0.01910523, 0.20013368, 0.79926873, 0.9187036 , 0.7073234 ,
       0.17688827, 0.81805105, 0.97486872, 0.91008892, 0.37734679,
       0.47281161, 0.36055579, 0.49296064, 0.15027437, 0.10238684,
       0.85480394, 0.51235525, 0.35313925, 0.82022373, 0.58041095,
       0.86012199, 0.83164723, 0.87071591, 0.84480853, 0.88742564])

# 
2.Create an array of 20 linear spaced points between 0 and 1



In [6]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

# 
3.Declare a numpy array of values from 1 to 100 and make it into 10*10 matrix

In [34]:
import numpy as np
array = np.arange(100).reshape(10,10)
array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

# 
4.Using the previously defind matrix print rows 1,5,6

In [8]:
print(array[[1,5,6]])

[[10 11 12 13 14 15 16 17 18 19]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]]


# 
5.Using the previously defined matrix print elements from 3rd row to 10th row

In [35]:
print(array[3:])

[[30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


# 
6.Using the previously defined matrix print all the elements from 4th row to 8th row

In [16]:
print(array[0:10,3:8])

[[ 3  4  5  6  7]
 [13 14 15 16 17]
 [23 24 25 26 27]
 [33 34 35 36 37]
 [43 44 45 46 47]
 [53 54 55 56 57]
 [63 64 65 66 67]
 [73 74 75 76 77]
 [83 84 85 86 87]
 [93 94 95 96 97]]


# 
7.Using the same matrix print values from 3rd row 2nd column to 5th row 8th column

In [17]:
print(array[2:5,1:8])

[[21 22 23 24 25 26 27]
 [31 32 33 34 35 36 37]
 [41 42 43 44 45 46 47]]


#
8.Write a code to generate random 1000 numbers each in range (0,1) such that the count of all random points like are almost same

In [36]:
np.random.rand(100)

array([1.30693617e-01, 1.15471021e-01, 1.99546054e-01, 2.27127671e-01,
       8.61514676e-01, 1.12523794e-01, 7.22072526e-01, 4.87486787e-01,
       8.25082111e-01, 2.41960763e-01, 2.87188643e-01, 2.72622262e-01,
       4.10920633e-01, 5.89002430e-01, 4.44607575e-01, 1.83067815e-01,
       6.36160165e-01, 2.66233762e-01, 9.76705611e-01, 4.09078428e-01,
       4.96178068e-01, 3.48174361e-01, 2.60313026e-01, 3.37999361e-01,
       8.91033088e-01, 7.22149121e-01, 2.38457073e-01, 9.87234753e-01,
       3.40525759e-01, 7.63301608e-01, 4.86259730e-01, 4.55528521e-01,
       2.89183089e-01, 9.48936150e-01, 5.46028538e-01, 9.17914969e-01,
       5.30411043e-01, 8.92675079e-01, 7.94582784e-01, 3.16205738e-01,
       8.95229568e-01, 8.55609811e-01, 5.89938821e-01, 2.83412616e-01,
       4.15081096e-01, 3.06990621e-01, 8.13722682e-02, 1.43428292e-02,
       1.96465030e-01, 4.44881104e-01, 9.39373446e-01, 6.83907239e-01,
       4.07142558e-01, 3.59498806e-01, 9.57777591e-01, 6.30065566e-01,
      

In [37]:
a = np.array([[7, 2], [5, 4]])
np.mean(a)

4.5

In [38]:
np.median(a)

4.5

In [39]:
np.std(a)

1.8027756377319946

In [40]:
a = np.array([[7, 1, 1, 7],
             [9, 4, 3, 8],
             [6, 1, 9, 7],
             [9, 7, 2, 5],
             [5, 1, 5, 9]])
a

array([[7, 1, 1, 7],
       [9, 4, 3, 8],
       [6, 1, 9, 7],
       [9, 7, 2, 5],
       [5, 1, 5, 9]])

In [41]:
from scipy import stats
stats.mode(a)

ModeResult(mode=array([[9, 1, 1, 7]]), count=array([[2, 3, 1, 2]]))